# Collections & Arrays

## Lists

In [ ]:
# Created with [] or list()
# Ordered
# Mutable
# Allow duplicates
# Allow nesting

empty_list = []
bracket_list = [1, 2, "four", 3, 3, "four"]
nested_list = ["a", "b", [1, 2]] # Also referred to as multi dimentional list
function_list_from_str = list("abc123abc")
function_list_from_tuple = list((1, 2, "three"))

# Heads up: list([iterable])
number_range = range(0, 6)
number_range_list = list(number_range)
#print(f"number_range_list = {number_range_list}")

# This will break
#faulty_function_list = list(1)
#fixed_function_list = list([1])

In [ ]:
### Accessing elements
my_list = ["a", "b", 1, 2]

# list_identifier[item_index] > also negative indexes (backwards)!
#print(my_list[-3])

### Adding and removing items

# append()
#my_list.append("new element")
#print(my_list)

# insert()
#my_list.insert(6, "first element")
#print(my_list)

# pop()
#my_list.pop()
#print(my_list)
#my_list.pop(3)

# remove()
try:
    my_list.remove("n")
except ValueError as ve:
    print(str(ve))

# del > remove indexed element
del my_list[2]
    
# Membership (in/not in)
#print("a" in my_list)

In [ ]:
### Concatenating and combining lists
list_to_extend = [1, 2, 3] # Very poor naming convention!
list_to_add = [4, 5, 6]

# + (plus)
# Can only concatenate list to another list
#print(list_to_extend + list_to_add)
# This will fail, cannot add set to the list
list_to_extend + {1,2}

# extend()
# Appends all items in any provided iterable (e.g., tuple, string, list etc)
#list_to_extend.extend(list_to_add)
#print(list_to_extend)
listA = [1,2,3]
listA.extend("abc") # string
listA.extend(("Name", 45)) # tuple
listA.extend({4,5,6}) # set
listA.extend([0, -1]) # list
print(listA)

### Sorting
unsorted_list = ["d", "a", "c", "b"]
#print(unsorted_list)
#unsorted_list.sort()
#print(unsorted_list)

### Slicing
my_list = [1, 2, 3, 4, 5, 6]
#print(my_list[::-1])

### Reverse
my_list = ["8", "7", "6", "5"]
my_list.reverse()
#print(my_list)

## Sets

In [ ]:
# Created with {} with content!! or set()
# Unordered
# Mutable (heads up! but not the elements!)
# Do NOT allow duplicates
# Do NOT allow nesting > cannot contian mutable elements

empty_set = set() # Cannot use {} because this creates dict!
curly_set = {1, 2, "four", 3, 3, "four"}
function_set = set("abc123abc")

# These will fail; mutable element in set
#mutable_set_set = {{"one", "two"}} # Nesting not allowed
#mutable_list_set = {["one", "two"]}
#mutable_dict_set = {{"one" : 1, "two" : 2}}

# Heads up: set([iterable])
number_range_set = set(range(0, 6))
#print(f"number_range_set = {number_range_set}")

# This will break
#faulty_function_set = set(1)

In [ ]:
### Accessing items
# Heads up! No way to access items in a set by referring to an index or a key!
fruit_set = {"apple", "orange", "pear"}

fruit_list = list(fruit_set)
fruit_list.append("melon")
fruit_list.append("apple")
print(fruit_list)

fruit_set = set(fruit_list)
print(fruit_set)

In [ ]:
### Adding and removing items

# add() - Remember: no duplicates!
#fruit_set.add("kiwi")
#print(fruit_set)


# update([iterable]) - Heads up! requires iterable!
#fruit_set.update({"grape"})
print(fruit_set)

# pop() - Heads up! Pops random element
#fruit_set.pop()
#print(fruit_set)

# remove()
try:
    fruit_set.remove("pear")
except KeyError as ke:
    print("Error", str(ke))

print(fruit_set)

In [ ]:
### Mathematical operations
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

# union()
print(set_a.union(set_b))

# difference()
print(set_a.difference(set_b))


# + A few more, check out course content part 2.2

## Tuples

In [ ]:
# Created with comma-seperated list, () or tuple()
# Ordered
# Immutable
# Allow duplicates
# Allow nesting

empty_tuple = ()
comma_separated_tuple = "Age",2
parantesis_tuple = ("Age", 4)
function_tuple = tuple(["Age", 6])

# You cannot change a tuple (immutable)
tuple_with_list = ([1,2], "abc")
print(tuple_with_list)

# This however will work (!!), because we are not changing the content of the tuple, but the list.
# tuple_with_list[0] references the list in our tuple. The list is mutable. We add an element to it.
tuple_with_list[0].append(3)
print(tuple_with_list)

# This however will fail, because we're changing the content of the tuple,
# i.e. replacing the first element with a new one (reassigning the first element in the tuple).
tuple_with_list[0] = [1,2,3]

# If you expect change, better off not using tuple, but if you really have to:
student_tuple = ("Reza", [104, 204])
#student_name = student_tuple[0]
#student_courses = student_tuple[1]
#student_courses.append(304)
#student_tuple = (student_name, student_courses)
#print(student_tuple)


# Convert to list, change, convert back
tupX = (1,2,3)
#print(tupX)
listX = list(tupX)
#print(listX)
listX.append(4)
tupX = tuple(listX)
#print(tupX)

In [ ]:
### Unpacking (access)
tup = (1,2,3)
one,two,three = tup # unpacking

# Unpacking uknown length tuple > starred assignment (*)
# Done by placing a star (*) on the left of a variable name in a multiple assignment,
#   seperated by comma (,)
#   and having any iterable on the right of the assignment.
# The variable name with the star gets elements from the iterable as a list.
another_tup = (1,2,3,4,5,6)
# First element in tuple is unpacked to variable "one"
# All remaning elements are put in a list "rest"
one, *rest = another_tup
#print(one)
#print(rest)

# Heads up! Special syntax for starred assignment
*unpacked, = another_tup
(*unpacked,) = another_tup

In [ ]:
### A few useful methods
tup = (1,2,1,3,3,2,2)

# count()
#print(tup.count(3))


# index()
print(tup.index(3))

In [ ]:
### Slicing
# Just like list (as long as tuple content is iterable)
tup = ("abcdef")
sliced_tup = tup[0:2]
print(type(sliced_tup))

## Dictionaries

In [ ]:
# Created with {} or dict()
# Store data in key : value pairs
# Keys must be immutable
# Keys are case sensitive
# Ordered (Python >= v3.7)
# Mutable
# Do NOT allow duplicate keys (values are not checked for duplicity)
# Allow nesting

empty_dict = {}
duplicate_key_dict = {"Reza" : 45, "Reza" : 65}
duplicate_value_dict = {"Reza" : 45, "Ola" : 45}
function_dict = dict([("Rolf", 45), ("Kari", 38)])
another_function_dict = dict(Name = "Reza", Age = 45, Country = "Norway")

In [ ]:
### Accessing elements
student_dict = {"Truls" : [1 , 2], "Morten" : [3, 4]}

# With brackets []
#print(student_dict["Truls"])


# get()
#print(student_dict.get("Truls"))
#print(student_dict.get("Trul"))
#print(student_dict.get("Tru", "Not found"))

### Adding/removing items

# With []
#student_dict[3] = 60
#student_dict["3"] = 60
print(student_dict)

# update({dict}) > multiple elements


# setdefault()
print(student_dict.setdefault("Reza"))
print(student_dict)

# pop(key)


# del dict[key]


# Membership (in/not in)
# Heads up! Only checks keys
#print("Reza" in student_dict)

# "Search" by value
# Use items() method to get an iterable for the key/value pairs in a dict.
# Find the first student with a top grade (3)
student_grades = {"Ola": 1, "Kari": 2, "Per" : 3, "Rolf" : 2, "Louise" : 1, "Kristian" : 2, "Iben" : 3}
for name, grade in student_grades.items():
    # Check the value
    if grade == 3:
        print(name)
        break